"""Sprint L1 of the Code of Law loop: the writer and the slot.

The operator's ask (request 4110, decision 4114): do for every project what
a hand-maintained rules file does for one - a per-project law file, fired at
session start on every host, maintained by godmode itself. L1 is the writer
and the slot: `law compile` folds every lesson that carries a generalized
guard into a bounded `GODMODE-CODE-OF-LAW.md` with provenance, a wrapper
skill carries it to hook-less hosts, the file is a bound authority role so
the charter, `attest` and the required-sources counter consume it with no
new machinery, and the SessionStart brief carries the top laws.

Doctrine constraints, live in this module:
- The file is GENERATED and says so; a hand edit is overwritten. The hand
  file this generalizes rotted exactly because nothing regenerated it.
- Bounded, and the bound is stated in the artifact (no silent caps): laws
  beyond the cap are counted in the file itself.
- Deterministic: same archive, same bytes - no timestamps, no randomness -
  so `bindings`-style drift checks and git diffs stay meaningful.
- Counts and reviewed prose only. A lesson's value and guard were written
  at recording time under the archive's own secret scan; nothing here reads
  prompts or source bodies.

Detectors, receipts and the promotion ladder are L2/L3 (see the spec);
until then every compiled law is ADVISORY and its provenance is the lesson
it came from.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

LAW_FILENAME = "GODMODE-CODE-OF-LAW.md"
SKILL_DIRNAME = "godmode-code-of-law"
LAW_CAP = 24
GUARD_CHARS = 200
WHY_CHARS = 160

_HEADER = f"""# GODMODE CODE OF LAW

Generated by `godmode law compile` from this project's archive. Do not
hand-edit: the next compile overwrites this file. Each law is a lesson this
project recorded with a generalized guard; the sequence number is its
provenance in the hash-chained archive (`godmode slice`/`history` to read
it back). Laws are ADVISORY until the promotion ladder ships; follow the
guard, and when a guard is wrong, retire the lesson rather than ignoring
the law.
"""


def _ellipsize(text: str, limit: int) -> str:
    flattened = " ".join(str(text).split())
    if len(flattened) <= limit:
        return flattened
    return flattened[: limit - 1].rstrip() + "…"


def _guarded_lessons(archive: Any) -> list[dict[str, Any]]:
    # Dedup by subject, newest record wins (2026-08-29): a promotion retried
    # after a parse error wrote the same law twice, and two 2026-08-11
    # lessons had shared a subject since before the compiler existed - each
    # rendered as its own law. One subject, one law, and appending a
    # retired record now actually retires the law (the newest record is the
    # subject's state, the same rule status remaining already follows).
    by_subject: dict[str, dict[str, Any]] = {}
    for record in archive.read_events():
        if record.get("kind") != "lesson":
            continue
        current = by_subject.get(str(record.get("subject", "")))
        if current is None or int(record.get("sequence", 0)) > current["sequence"]:
            by_subject[str(record.get("subject", ""))] = {
                "sequence": int(record.get("sequence", 0)), "record": record}
    lessons = []
    for kept in by_subject.values():
        record = kept["record"]
        data = record.get("data") or {}
        if str(data.get("status", "active")) in ("retired", "candidate"):
            continue
        guard = str(data.get("generalized_guard") or "").strip()
        if not guard:
            continue
        lessons.append({
            "sequence": int(record.get("sequence", 0)),
            "subject": str(record.get("subject", ""))[:120],
            "guard": guard,
            "why": str(data.get("value", "")),
            "recorded_at": str(record.get("recorded_at", ""))[:10],
        })
    lessons.sort(key=lambda lesson: lesson["sequence"], reverse=True)
    return lessons


def _delivered_seqs(archive: Any) -> set[int]:
    delivered: set[int] = set()
    for record in archive.read_events():
        if record.get("kind") == "action" and record.get("subject") == "laws-delivered":
            for seq in (record.get("data") or {}).get("law_seqs") or []:
                delivered.add(int(seq))
    return delivered


def top_laws(archive: Any, k: int) -> list[dict[str, Any]]:
    """The k newest laws, bounded for the brief's budget. `dormant` means no
    delivery receipt has ever named this law - L3's decay input, flagged
    rather than silently carried."""
    delivered = _delivered_seqs(archive)
    return [
        {"subject": lesson["subject"], "guard": _ellipsize(lesson["guard"], GUARD_CHARS),
         "seq": lesson["sequence"], "dormant": lesson["sequence"] not in delivered}
        for lesson in _guarded_lessons(archive)[: max(0, k)]
    ]


def _render(laws: list[dict[str, Any]], dropped: int, cap: int) -> str:
    lines = [_HEADER]
    for number, lesson in enumerate(laws, 1):
        lines.append(f"## Law {number} - {lesson['subject']}  [ADVISORY]")
        lines.append(f"Guard: {_ellipsize(lesson['guard'], GUARD_CHARS)}")
        lines.append(f"Why: {_ellipsize(lesson['why'], WHY_CHARS)}")
        lines.append(
            f"Provenance: seq:{lesson['sequence']}, recorded {lesson['recorded_at']}")
        lines.append("")
    if dropped:
        lines.append(
            f"{dropped} older guarded lesson(s) beyond the cap of {cap} are not "
            "rendered here - raise the cap, or retire laws that no longer earn "
            "their place.")
        lines.append("")
    return "\n".join(lines)


_SKILL_BODY = f"""---
name: {SKILL_DIRNAME}
description: Use at the start of every session and before every new task - the project's generated Code of Law; read {LAW_FILENAME} at the project root and follow its guards before acting.
---

# The project's Code of Law

Read `{LAW_FILENAME}` at the project root before substantive work. Every law
was recorded by this project from its own corrections and carries its
archive provenance. Follow each law's guard; when one seems wrong, say so
and retire the underlying lesson (`godmode lessons`) rather than silently
ignoring it. Regenerate after new lessons with `godmode law compile`.
"""


# Obligation 4521: a candidate was built from a passage the operator
# explicitly said to disregard. A prompt that carries a disregard marker
# feeds neither detector - the operator already ruled on it.
_DISREGARD_MARKERS = ("ignore this", "disregard this", "by mistake",
                      "entered here by mistake")


_CORRECTION_MARKERS = frozenset({
    "wrong", "again", "missed", "incorrect", "mistake", "revert", "undo",
})
_CORRECTION_THRESHOLD = 2

# loop-engineering's reliability discipline, absorbed 2026-08-28: nothing
# escalates on one observation. A candidate cluster is promotable only after
# the same correction recurs in this many DISTINCT sessions.
PROMOTION_SESSIONS = 3


def record_correction_candidate(archive: Any, prompt: str, *,
                                session: str | None = None) -> dict[str, Any] | None:
    """The operator-correction detector (Sprint L2, decision 4114).

    A correction-shaped prompt - at least two distinct correction markers -
    writes a law CANDIDATE: a lesson with status "candidate", carrying the
    prompt's keywords and digest, never its sentence (the 4018 privacy
    decision holds here too). A candidate has no guard, so `law compile`
    never renders it; review drafts the guard, the ladder (L3) promotes it.
    Returns None for an ordinary prompt, a secret-shaped one, or an empty
    one - the detector is quiet by contract.
    """
    from .godmode_requests import _keywords, digest
    from .godmode_sentinel import find_secret_shapes

    flattened = " ".join(str(prompt).split())
    if not flattened or find_secret_shapes(flattened):
        return None
    if any(marker in flattened.lower() for marker in _DISREGARD_MARKERS):
        return None
    words = {w.lower() for w in flattened.replace(",", " ").split()}
    markers = sorted(_CORRECTION_MARKERS & words)
    if len(markers) < _CORRECTION_THRESHOLD:
        return None
    identifier = digest(flattened)
    return archive.append(
        "lesson",
        f"correction:{identifier[:12]}",
        {
            "status": "candidate",
            "value": "operator corrected the agent (counts only); draft a guard "
                     "at review, promote via the ladder",
            "keywords": sorted(_keywords(flattened))[:24],
            "markers": markers,
            "session": session,
            "digest": identifier,
        },
        evidence=[],
    )


_INSTRUCTION_PHRASES = ("from now on", "going forward", "every time",
                        "each time", "in every", "make sure you always")
_INSTRUCTION_WORDS = frozenset({"always", "never", "whenever"})
# S11-E (two live chat-noise captures 2026-08-29, e.g. "whenever ready: 9
# fragments ..."): a standing rule has a marker AND an imperative verb close
# behind it; a marker floating in conversation does not.
_INSTRUCTION_VERBS = frozenset({
    "run", "include", "record", "keep", "use", "check", "preview", "write",
    "add", "grade", "read", "cite", "update", "close", "open", "test",
    "verify", "review", "follow", "state",
})


def _verb_follows_marker(low: str, hit: str) -> bool:
    index = low.find(hit)
    if index < 0:
        return False
    tail = low[index + len(hit):].split()
    window = {token.strip(".,;:!?\"'()") for token in tail[:5]}
    return bool(window & _INSTRUCTION_VERBS)


def record_instruction_candidate(archive: Any, prompt: str, *,
                                 session: str | None = None) -> dict[str, Any] | None:
    """S6 (obligation 4435): the FIRST telling, not the second.

    Field report 2026-08-28: an operator's standing instruction lived in
    harness memory godmode cannot read, and was dropped for three reports;
    the correction detector only fires when the operator has to say it
    AGAIN. An instruction-shaped prompt - a standing-rule marker like
    "always"/"from now on" - becomes a candidate on first utterance, same
    privacy contract as corrections (keywords and digest, never the
    sentence). An explicit directive is stronger evidence than an inferred
    correction, so its cluster is promotable after ONE session instead of
    the correction ladder's three; the guard is still reviewed prose at
    promotion time.
    """
    from .godmode_requests import _keywords, digest
    from .godmode_sentinel import find_secret_shapes

    flattened = " ".join(str(prompt).split())
    if not flattened or find_secret_shapes(flattened):
        return None
    low = flattened.lower()
    if any(marker in low for marker in _DISREGARD_MARKERS):
        return None
    if len(low.split()) < 4:
        return None
    words = {w.strip(".,;:!?") for w in low.split()}
    # S11-E fix within the fix: check EVERY matching marker for a following
    # imperative verb, not only the first - "always include X in every
    # report" matches the phrase "in every" first, whose window holds no
    # verb, while "always" a few words earlier does.
    hits = [phrase for phrase in _INSTRUCTION_PHRASES if phrase in low]
    hits += [w for w in sorted(_INSTRUCTION_WORDS) if w in words]
    if not hits:
        return None
    hit = next((h for h in hits if _verb_follows_marker(low, h)), None)
    if hit is None:
        # No marker has an imperative verb behind it: conversation, not a
        # standing rule (S11-E) - the live false captures all fail here.
        return None
    identifier = digest(flattened)
    return archive.append(
        "lesson",
        f"instruction:{identifier[:12]}",
        {
            "status": "candidate",
            "origin": "instruction",
            "value": "operator stated a standing instruction (counts only); "
                     "draft a guard at review - promotable after one session",
            "keywords": sorted(_keywords(flattened))[:24],
            "markers": [hit],
            "session": session,
            "digest": identifier,
        },
        evidence=[],
    )


def law_candidates(archive: Any) -> list[dict[str, Any]]:
    """Candidates clustered read-time by keyword identity, so a repeated
    correction increments a counter instead of splitting the promotion
    ladder's own evidence across duplicates (dedup-or-increment)."""
    clusters: dict[frozenset[str], dict[str, Any]] = {}
    # A promoted cluster is consumed (2026-08-29): promotion appends the
    # law but left the candidate records standing, so the cluster stayed
    # "promotable" forever and invited a second, duplicate promotion.
    promoted: set[int] = set()
    for record in archive.read_events():
        if record.get("kind") != "lesson":
            continue
        origin = (record.get("data") or {}).get("promoted_from")
        if origin is not None:
            promoted.add(int(origin))
    dismissed: dict[str, bool] = {}
    for record in archive.read_events():
        if record.get("kind") == "lesson":
            dismissed[str(record.get("subject", ""))] = (
                str((record.get("data") or {}).get("status")) == "retired")
    for record in archive.read_events():
        if record.get("kind") != "lesson":
            continue
        data = record.get("data") or {}
        if str(data.get("status")) != "candidate":
            continue
        if dismissed.get(str(record.get("subject", ""))):
            # S11 follow-up: a candidate whose subject was later retired is
            # DISMISSED - the pre-precision chat-noise captures needed a way
            # out that was not promotion.
            continue
        key = frozenset(str(k) for k in (data.get("keywords") or []))
        if not key:
            continue
        cluster = clusters.setdefault(key, {
            "keywords": sorted(key), "occurrences": 0, "sessions": set(),
            "first_seq": int(record.get("sequence", 0)),
            "origin": "correction",
        })
        if str(data.get("origin") or "") == "instruction":
            cluster["origin"] = "instruction"
        cluster["occurrences"] += 1
        cluster["last_seq"] = int(record.get("sequence", 0))
        session = data.get("session")
        if session:
            cluster["sessions"].add(str(session))
    ranked = []
    for cluster in clusters.values():
        if cluster["first_seq"] in promoted:
            continue
        cluster["distinct_sessions"] = len(cluster.pop("sessions"))
        # An explicit standing instruction promotes after one session; an
        # inferred correction still climbs the three-session ladder.
        needed = 1 if cluster.get("origin") == "instruction" else PROMOTION_SESSIONS
        cluster["promotable"] = cluster["distinct_sessions"] >= needed
        ranked.append(cluster)
    ranked.sort(key=lambda c: (-c["occurrences"], c["first_seq"]))
    return ranked


def promote_candidate(archive: Any, first_seq: int, *, guard: str,
                      subject: str) -> dict[str, Any]:
    """Promote a candidate cluster into a law - a guarded, active lesson.

    The guard is REVIEWED prose written at promotion time (a candidate
    carries keywords, never a sentence worth enshrining verbatim), and the
    ladder holds: below PROMOTION_SESSIONS distinct sessions, promotion is
    refused rather than discouraged. HARD enforcement stays with the
    charter; every promoted law is ADVISORY here.
    """
    from .godmode_errors import ArchiveError

    guard = " ".join(str(guard).split())
    subject = str(subject).strip()
    if not guard or not subject:
        raise ArchiveError("Promotion needs --guard and --subject, both non-empty")
    cluster = next(
        (c for c in law_candidates(archive) if c["first_seq"] == int(first_seq)), None)
    if cluster is None:
        raise ArchiveError(
            f"No candidate cluster starts at seq {first_seq}; `law candidates` lists them")
    if not cluster["promotable"]:
        raise ArchiveError(
            f"Cluster at seq {first_seq} has recurred in {cluster['distinct_sessions']} "
            f"distinct session(s); the ladder requires {PROMOTION_SESSIONS} - "
            "reliability first, promotion second")
    return archive.append(
        "lesson", subject,
        {
            "status": "active",
            "value": ("promoted from a correction cluster (keywords: "
                      + ", ".join(cluster["keywords"][:10]) + ")"),
            "generalized_guard": guard,
            "promoted_from": cluster["first_seq"],
            "occurrences": cluster["occurrences"],
            "distinct_sessions": cluster["distinct_sessions"],
        },
        evidence=[f"seq:{cluster['first_seq']}", f"seq:{cluster['last_seq']}"],
    )


def debrief(archive: Any) -> dict[str, Any]:
    """The amendment loop (S10; loopy 4112's adopted-but-unbuilt half).

    Reads the archive once and answers, per law: how often was it DELIVERED
    (receipts), was it ever CITED (a later record naming its seq), and did
    the SAME correction recur AFTER a delivery (the law was shown and the
    behaviour repeated - a law that is not working). Recommendations are
    triaged the maintainer-orchestrator way: promoting a ready candidate is
    autonomous (the ladder already gates it); amending or retiring a law is
    needs-operator, because a guard is reviewed prose. The report states
    its own read window and stopping reason (loop-engineering's honest
    stops), and a counts-only receipt is appended so the next debrief
    starts where this one ended and staleness is measurable.
    """
    records = archive.read_events()
    last_debrief = 0
    for record in records:
        if record.get("kind") == "action" and record.get("subject") == "law-debrief":
            last_debrief = int(record.get("sequence", 0))
    laws = _guarded_lessons(archive)
    delivered: dict[int, int] = {}
    last_delivery: dict[int, int] = {}
    for record in records:
        if record.get("kind") == "action" and record.get("subject") == "laws-delivered":
            for seq in (record.get("data") or {}).get("law_seqs") or []:
                delivered[int(seq)] = delivered.get(int(seq), 0) + 1
                last_delivery[int(seq)] = int(record.get("sequence", 0))
    cited: dict[int, int] = {}
    for record in records:
        for reference in record.get("evidence") or []:
            text = str(reference)
            if text.startswith("seq:"):
                try:
                    cited[int(text[4:])] = cited.get(int(text[4:]), 0) + 1
                except ValueError:
                    pass
    from .godmode_sources import _salient_words

    candidates = [r for r in records
                  if r.get("kind") == "lesson"
                  and str((r.get("data") or {}).get("status")) == "candidate"]
    entries = []
    amend, retire = [], []
    for law in laws:
        seq = law["sequence"]
        vocabulary = _salient_words(f"{law['subject']} {law['guard']}")
        recurrences = [
            int(c.get("sequence", 0)) for c in candidates
            if int(c.get("sequence", 0)) > last_delivery.get(seq, 0)
            and last_delivery.get(seq)
            and len(_salient_words(" ".join(
                str(k) for k in (c.get("data") or {}).get("keywords") or []))
                & vocabulary) >= 3
        ]
        entry = {
            "seq": seq,
            "subject": law["subject"][:80],
            "delivered": delivered.get(seq, 0),
            "cited": cited.get(seq, 0),
            "recurred_after_delivery": recurrences[:5],
        }
        if len(recurrences) >= 2:
            entry["recommendation"] = "amend-guard"
            amend.append(entry)
        elif delivered.get(seq, 0) >= 3 and not cited.get(seq) and not recurrences:
            entry["recommendation"] = "retire-candidate"
            retire.append(entry)
        else:
            entry["recommendation"] = "keep"
        entries.append(entry)
    promotable = [c["first_seq"] for c in law_candidates(archive) if c["promotable"]]
    receipt = archive.append("action", "law-debrief", {
        "window": [last_debrief, int(records[-1]["sequence"]) if records else 0],
        "laws": len(laws), "amend": len(amend), "retire": len(retire),
        "promotable": len(promotable),
    }, evidence=[])
    return {
        "window": {"from_seq": last_debrief,
                   "to_seq": int(records[-1]["sequence"]) if records else 0},
        "stopping_reason": "window-exhausted",
        "laws": entries,
        "autonomous": {"promote_ready": promotable,
                       "note": "the ladder already gates these; `law promote` acts"},
        "needs_operator": {
            "amend_guard": [e["seq"] for e in amend],
            "retire_candidate": [e["seq"] for e in retire],
            "note": "a guard is reviewed prose - amend by appending a lesson "
                    "with the same subject (newest record wins), retire by "
                    "appending status retired",
        },
        "receipt_seq": receipt["sequence"],
    }


_DEBRIEF_STALE_AFTER = 300


def debrief_status(archive: Any) -> dict[str, Any]:
    """S11-A: the meta-loop's own staleness gauge. The first live debrief ran
    2026-08-29 and nothing would have prompted a second - now `law show` and
    the brief carry how many records have landed since the last receipt."""
    records = archive.read_events()
    last = 0
    for record in records:
        if record.get("kind") == "action" and record.get("subject") == "law-debrief":
            last = int(record.get("sequence", 0))
    latest = int(records[-1]["sequence"]) if records else 0
    since = latest - last if last else latest
    return {
        "last_receipt_seq": last or None,
        "records_since": since,
        "stale": last == 0 or since > _DEBRIEF_STALE_AFTER,
    }


def amend_law(archive: Any, law_seq: int, guard: str) -> dict[str, Any]:
    """S11-D: execute a debrief amendment without hand-crafted appends.

    Appends a lesson with the SAME subject as the law at `law_seq` carrying
    the new reviewed guard; newest-wins dedup makes it the law. Refuses an
    empty guard, an unknown sequence, and a subject whose current state is
    retired or candidate - amendment is for living laws."""
    from .godmode_errors import ArchiveError

    guard = " ".join(str(guard).split())
    if not guard:
        raise ArchiveError("Amendment needs a non-empty reviewed guard")
    target = None
    latest_by_subject: dict[str, dict[str, Any]] = {}
    for record in archive.read_events():
        if record.get("kind") != "lesson":
            continue
        latest_by_subject[str(record.get("subject", ""))] = record
        if int(record.get("sequence", 0)) == int(law_seq):
            target = record
    if target is None:
        raise ArchiveError(f"No lesson record at seq {law_seq}")
    subject = str(target.get("subject", ""))
    current = latest_by_subject.get(subject) or {}
    status = str((current.get("data") or {}).get("status", "active"))
    if status in ("retired", "candidate"):
        raise ArchiveError(
            f"'{subject[:60]}' is {status}; amendment is for living laws")
    return archive.append(
        "lesson", subject,
        {
            "status": "active",
            "generalized_guard": guard,
            "value": f"amended from seq {int(law_seq)} (S11 law amend)",
            "amended_from": int(law_seq),
        },
        evidence=[f"seq:{int(law_seq)}"],
    )


def record_delivery(archive: Any, laws: list[dict[str, Any]], *,
                    session: str | None = None) -> dict[str, Any] | None:
    """The delivery receipt: which laws the brief carried, counts only.

    The denominator (loopy's receipts, via the L2 spec): without a record
    of delivery, "violated 0" cannot be told apart from "never seen".
    """
    if not laws:
        return None
    return archive.append(
        "action",
        "laws-delivered",
        {
            "delivered": len(laws),
            "law_seqs": [int(law.get("seq", 0)) for law in laws],
            "session": session,
        },
        evidence=[],
    )


def compile_laws(archive: Any, project: Path | str, *, cap: int = LAW_CAP) -> dict[str, Any]:
    """Fold guarded lessons into the law file and its wrapper skill."""
    root = Path(project)
    lessons = _guarded_lessons(archive)
    skipped = sum(
        1 for record in archive.read_events()
        if record.get("kind") == "lesson"
        and not str((record.get("data") or {}).get("generalized_guard") or "").strip()
    )
    kept, dropped = lessons[:cap], max(0, len(lessons) - cap)
    (root / LAW_FILENAME).write_text(_render(kept, dropped, cap), encoding="utf-8")
    skill_dir = root / "skills" / SKILL_DIRNAME
    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(_SKILL_BODY, encoding="utf-8")
    return {
        "laws": len(kept),
        "dropped_over_cap": dropped,
        "skipped_without_guard": skipped,
        "cap": cap,
        "path": LAW_FILENAME,
        "skill": f"skills/{SKILL_DIRNAME}/SKILL.md",
    }
