"""Sprint L1 of the Code of Law loop: the writer and the slot.

The operator's ask (request 4110, decision 4114): do for every project what
a hand-maintained rules file does for one - a per-project law file, fired at
session start on every host, maintained by godmode itself. L1 is the writer
and the slot: `law compile` folds every lesson that carries a generalized
guard into a bounded `GODMODE-CODE-OF-LAW.md` with provenance, a wrapper
skill carries it to hook-less hosts, the file is a bound authority role so
the charter, `attest` and the required-sources counter consume it with no
new machinery, and the SessionStart brief carries the top laws.

Doctrine constraints, live in this module:
- The file is GENERATED and says so; a hand edit is overwritten. The hand
  file this generalizes rotted exactly because nothing regenerated it.
- Bounded, and the bound is stated in the artifact (no silent caps): laws
  beyond the cap are counted in the file itself.
- Deterministic: same archive, same bytes - no timestamps, no randomness -
  so `bindings`-style drift checks and git diffs stay meaningful.
- Counts and reviewed prose only. A lesson's value and guard were written
  at recording time under the archive's own secret scan; nothing here reads
  prompts or source bodies.

Detectors, receipts and the promotion ladder are L2/L3 (see the spec);
until then every compiled law is ADVISORY and its provenance is the lesson
it came from.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

LAW_FILENAME = "GODMODE-CODE-OF-LAW.md"
SKILL_DIRNAME = "godmode-code-of-law"
LAW_CAP = 24
GUARD_CHARS = 200
WHY_CHARS = 160

_HEADER = f"""# GODMODE CODE OF LAW

Generated by `godmode law compile` from this project's archive. Do not
hand-edit: the next compile overwrites this file. Each law is a lesson this
project recorded with a generalized guard; the sequence number is its
provenance in the hash-chained archive (`godmode slice`/`history` to read
it back). Laws are ADVISORY until the promotion ladder ships; follow the
guard, and when a guard is wrong, retire the lesson rather than ignoring
the law.
"""


def _ellipsize(text: str, limit: int) -> str:
    flattened = " ".join(str(text).split())
    if len(flattened) <= limit:
        return flattened
    return flattened[: limit - 1].rstrip() + "…"


def _guarded_lessons(archive: Any) -> list[dict[str, Any]]:
    lessons = []
    for record in archive.read_events():
        if record.get("kind") != "lesson":
            continue
        data = record.get("data") or {}
        if str(data.get("status", "active")) == "retired":
            continue
        guard = str(data.get("generalized_guard") or "").strip()
        if not guard:
            continue
        lessons.append({
            "sequence": int(record.get("sequence", 0)),
            "subject": str(record.get("subject", ""))[:120],
            "guard": guard,
            "why": str(data.get("value", "")),
            "recorded_at": str(record.get("recorded_at", ""))[:10],
        })
    lessons.sort(key=lambda lesson: lesson["sequence"], reverse=True)
    return lessons


def top_laws(archive: Any, k: int) -> list[dict[str, Any]]:
    """The k newest laws, bounded for the brief's budget."""
    return [
        {"subject": lesson["subject"], "guard": _ellipsize(lesson["guard"], GUARD_CHARS),
         "seq": lesson["sequence"]}
        for lesson in _guarded_lessons(archive)[: max(0, k)]
    ]


def _render(laws: list[dict[str, Any]], dropped: int, cap: int) -> str:
    lines = [_HEADER]
    for number, lesson in enumerate(laws, 1):
        lines.append(f"## Law {number} - {lesson['subject']}  [ADVISORY]")
        lines.append(f"Guard: {_ellipsize(lesson['guard'], GUARD_CHARS)}")
        lines.append(f"Why: {_ellipsize(lesson['why'], WHY_CHARS)}")
        lines.append(
            f"Provenance: seq:{lesson['sequence']}, recorded {lesson['recorded_at']}")
        lines.append("")
    if dropped:
        lines.append(
            f"{dropped} older guarded lesson(s) beyond the cap of {cap} are not "
            "rendered here - raise the cap, or retire laws that no longer earn "
            "their place.")
        lines.append("")
    return "\n".join(lines)


_SKILL_BODY = f"""---
name: {SKILL_DIRNAME}
description: Use at the start of every session and before every new task - the project's generated Code of Law; read {LAW_FILENAME} at the project root and follow its guards before acting.
---

# The project's Code of Law

Read `{LAW_FILENAME}` at the project root before substantive work. Every law
was recorded by this project from its own corrections and carries its
archive provenance. Follow each law's guard; when one seems wrong, say so
and retire the underlying lesson (`godmode lessons`) rather than silently
ignoring it. Regenerate after new lessons with `godmode law compile`.
"""


def compile_laws(archive: Any, project: Path | str, *, cap: int = LAW_CAP) -> dict[str, Any]:
    """Fold guarded lessons into the law file and its wrapper skill."""
    root = Path(project)
    lessons = _guarded_lessons(archive)
    skipped = sum(
        1 for record in archive.read_events()
        if record.get("kind") == "lesson"
        and not str((record.get("data") or {}).get("generalized_guard") or "").strip()
    )
    kept, dropped = lessons[:cap], max(0, len(lessons) - cap)
    (root / LAW_FILENAME).write_text(_render(kept, dropped, cap), encoding="utf-8")
    skill_dir = root / "skills" / SKILL_DIRNAME
    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(_SKILL_BODY, encoding="utf-8")
    return {
        "laws": len(kept),
        "dropped_over_cap": dropped,
        "skipped_without_guard": skipped,
        "cap": cap,
        "path": LAW_FILENAME,
        "skill": f"skills/{SKILL_DIRNAME}/SKILL.md",
    }
